# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: avaamo_db

# test:
#   <<: *default
#   database: avaamo_db

# production:
#   <<: *default
#   database: avaamo_db
#   username: <%= ENV['HELLO_WORLD_DATABASE_USER'] %>
#   password: <%= ENV['HELLO_WORLD_DATABASE_PASSWORD'] %>
